from __future__ import annotations

from dataclasses import dataclass
from importlib import import_module
from math import pi
from typing import Any, Mapping

import numpy as np

from .domain import BearingCoefficientPoint, BearingGroup, BearingSpec, EngineeringError, RotorProject


@dataclass(slots=True, frozen=True)
class BearingCalculationResult:
    """Traceable result generated by a supported Bearing Studio model."""

    source_model: str
    application_class: str
    coefficients: tuple[BearingCoefficientPoint, ...]
    scalar_kc: tuple[float, float, float, float, float, float, float, float]
    metadata: dict[str, float | int | str | list[float]]
    note: str

    @property
    def speed_dependent(self) -> bool:
        return bool(self.coefficients)


class BearingStudioService:
    """Non-Qt engineering service behind the General / Parametric Bearing Studio.

    The service intentionally separates three operations:

    1. validate engineering inputs;
    2. calculate through the installed ROSS class;
    3. explicitly apply the result to one ``BearingSpec``.

    THD classes keep their specialized solvers. MagneticBearingElement is
    accepted here because its native ROSS constructor already owns the complete
    electromagnetic/PID coefficient model; time-domain feedback is qualified separately.
    """

    GENERAL_CLASSES = {
        "BearingElement",
        "BallBearingElement",
        "RollerBearingElement",
        "CylindricalBearing",
        "MagneticBearingElement",
    }

    def __init__(self, ross_module: Any | None = None) -> None:
        self.rs = ross_module

    def _ross(self) -> Any:
        if self.rs is None:
            self.rs = import_module("ross")
        return self.rs

    @staticmethod
    def _finite_positive(value: Any, name: str, *, allow_zero: bool = False) -> float:
        number = float(value)
        if not np.isfinite(number):
            raise EngineeringError(f"{name} must be finite; received {value!r}.")
        if allow_zero:
            if number < 0.0:
                raise EngineeringError(f"{name} must be non-negative; received {number:g}.")
        elif number <= 0.0:
            raise EngineeringError(f"{name} must be positive; received {number:g}.")
        return number

    @staticmethod
    def _finite(value: Any, name: str) -> float:
        number = float(value)
        if not np.isfinite(number):
            raise EngineeringError(f"{name} must be finite; received {value!r}.")
        return number

    @staticmethod
    def _matrix_kc(element: Any, frequency_rad_s: float) -> tuple[float, float, float, float, float, float, float, float]:
        k = np.asarray(element.K(float(frequency_rad_s)), dtype=float)
        c = np.asarray(element.C(float(frequency_rad_s)), dtype=float)
        if k.shape[0] < 2 or k.shape[1] < 2 or c.shape[0] < 2 or c.shape[1] < 2:
            raise EngineeringError("ROSS bearing model did not return a lateral 2x2 K/C block.")
        values = (
            float(k[0, 0]), float(k[0, 1]), float(k[1, 0]), float(k[1, 1]),
            float(c[0, 0]), float(c[0, 1]), float(c[1, 0]), float(c[1, 1]),
        )
        if not all(np.isfinite(value) for value in values):
            raise EngineeringError("ROSS bearing calculation returned a non-finite K/C coefficient.")
        return values

    @staticmethod
    def _point(rpm: float, values: tuple[float, float, float, float, float, float, float, float]) -> BearingCoefficientPoint:
        kxx, kxy, kyx, kyy, cxx, cxy, cyx, cyy = values
        return BearingCoefficientPoint(
            rpm=float(rpm),
            kxx=kxx,
            kxy=kxy,
            kyx=kyx,
            kyy=kyy,
            cxx=cxx,
            cxy=cxy,
            cyx=cyx,
            cyy=cyy,
        )

    @staticmethod
    def _bearing(project: RotorProject, index: int) -> BearingSpec:
        if not 0 <= int(index) < len(project.bearings):
            raise EngineeringError(f"Bearing index {index} is outside project bearing range.")
        return project.bearings[int(index)]

    def calculate(
        self,
        project: RotorProject,
        index: int,
        ross_class: str,
        inputs: Mapping[str, Any] | None = None,
    ) -> BearingCalculationResult:
        spec = self._bearing(project, index)
        inputs = dict(inputs or {})
        if ross_class not in self.GENERAL_CLASSES:
            raise EngineeringError(f"{ross_class} has no qualified Bearing Studio service.")

        if ross_class == "BearingElement":
            return self._calculate_kc(spec, inputs)
        if ross_class == "BallBearingElement":
            return self._calculate_ball(inputs)
        if ross_class == "RollerBearingElement":
            return self._calculate_roller(inputs)
        if ross_class == "MagneticBearingElement":
            return self._calculate_magnetic(project, inputs)
        return self._calculate_cylindrical(project, index, inputs)

    def _calculate_kc(self, spec: BearingSpec, inputs: dict[str, Any]) -> BearingCalculationResult:
        points = inputs.get("coefficients")
        if points is None:
            points = spec.coefficients
        points = list(points)
        if points:
            normalized: list[BearingCoefficientPoint] = []
            previous = -np.inf
            for row in points:
                point = row if isinstance(row, BearingCoefficientPoint) else BearingCoefficientPoint(**row)
                if not np.isfinite(point.rpm) or point.rpm < 0.0 or point.rpm <= previous:
                    raise EngineeringError("Bearing K/C table speeds must be finite, non-negative and strictly increasing.")
                values = (point.kxx, point.kxy, point.kyx, point.kyy, point.cxx, point.cxy, point.cyx, point.cyy)
                if not all(np.isfinite(value) for value in values):
                    raise EngineeringError(f"Bearing K/C row at {point.rpm:g} rpm contains a non-finite value.")
                normalized.append(point)
                previous = point.rpm
            rated = normalized[min(range(len(normalized)), key=lambda i: abs(normalized[i].rpm - inputs.get("rated_speed_rpm", normalized[i].rpm)))]
            scalar = (rated.kxx, rated.kxy, rated.kyx, rated.kyy, rated.cxx, rated.cxy, rated.cyx, rated.cyy)
            return BearingCalculationResult(
                source_model="BearingElement",
                application_class="BearingElement",
                coefficients=tuple(normalized),
                scalar_kc=scalar,
                metadata={"source_model": "BearingElement", "input_mode": "speed-dependent K/C table"},
                note="Direct K/C table validated without recomputation.",
            )

        scalar = (
            self._finite(inputs.get("kxx", spec.kxx), "Kxx"),
            self._finite(inputs.get("kxy", spec.kxy), "Kxy"),
            self._finite(inputs.get("kyx", spec.kyx), "Kyx"),
            self._finite(inputs.get("kyy", spec.kyy), "Kyy"),
            self._finite(inputs.get("cxx", spec.cxx), "Cxx"),
            self._finite(inputs.get("cxy", spec.cxy), "Cxy"),
            self._finite(inputs.get("cyx", spec.cyx), "Cyx"),
            self._finite(inputs.get("cyy", spec.cyy), "Cyy"),
        )
        return BearingCalculationResult(
            source_model="BearingElement",
            application_class="BearingElement",
            coefficients=(),
            scalar_kc=scalar,
            metadata={"source_model": "BearingElement", "input_mode": "constant K/C"},
            note="Constant direct K/C coefficients validated without recomputation.",
        )

    def _calculate_ball(self, inputs: dict[str, Any]) -> BearingCalculationResult:
        rs = self._ross()
        n_balls = int(inputs.get("n_balls", 8))
        if n_balls < 3:
            raise EngineeringError("Ball bearing requires at least 3 balls.")
        d_balls_m = self._finite_positive(inputs.get("d_balls_m", 0.03), "Ball diameter")
        static_load_n = self._finite_positive(inputs.get("static_load_n", 500.0), "Static load")
        contact_angle_rad = self._finite(inputs.get("contact_angle_rad", 0.0), "Contact angle")
        cxx = inputs.get("cxx")
        cyy = inputs.get("cyy")
        element = rs.BallBearingElement(
            n=0,
            n_balls=n_balls,
            d_balls=d_balls_m,
            fs=static_load_n,
            alpha=contact_angle_rad,
            cxx=None if cxx is None else self._finite_positive(cxx, "Cxx", allow_zero=True),
            cyy=None if cyy is None else self._finite_positive(cyy, "Cyy", allow_zero=True),
        )
        scalar = self._matrix_kc(element, 0.0)
        metadata: dict[str, float | int | str | list[float]] = {
            "source_model": "BallBearingElement",
            "n_balls": n_balls,
            "d_balls_m": d_balls_m,
            "static_load_n": static_load_n,
            "contact_angle_rad": contact_angle_rad,
        }
        if cxx is not None:
            metadata["cxx"] = float(cxx)
        if cyy is not None:
            metadata["cyy"] = float(cyy)
        return BearingCalculationResult(
            source_model="BallBearingElement",
            application_class="BallBearingElement",
            coefficients=(),
            scalar_kc=scalar,
            metadata=metadata,
            note="K/C calculated by ROSS BallBearingElement analytical model.",
        )

    def _calculate_roller(self, inputs: dict[str, Any]) -> BearingCalculationResult:
        rs = self._ross()
        n_rollers = int(inputs.get("n_rollers", 8))
        if n_rollers < 3:
            raise EngineeringError("Roller bearing requires at least 3 rollers.")
        roller_length_m = self._finite_positive(inputs.get("roller_length_m", 0.03), "Roller length")
        static_load_n = self._finite_positive(inputs.get("static_load_n", 500.0), "Static load")
        contact_angle_rad = self._finite(inputs.get("contact_angle_rad", 0.0), "Contact angle")
        cxx = inputs.get("cxx")
        cyy = inputs.get("cyy")
        element = rs.RollerBearingElement(
            n=0,
            n_rollers=n_rollers,
            l_rollers=roller_length_m,
            fs=static_load_n,
            alpha=contact_angle_rad,
            cxx=None if cxx is None else self._finite_positive(cxx, "Cxx", allow_zero=True),
            cyy=None if cyy is None else self._finite_positive(cyy, "Cyy", allow_zero=True),
        )
        scalar = self._matrix_kc(element, 0.0)
        metadata: dict[str, float | int | str | list[float]] = {
            "source_model": "RollerBearingElement",
            "n_rollers": n_rollers,
            "roller_length_m": roller_length_m,
            "static_load_n": static_load_n,
            "contact_angle_rad": contact_angle_rad,
        }
        if cxx is not None:
            metadata["cxx"] = float(cxx)
        if cyy is not None:
            metadata["cyy"] = float(cyy)
        return BearingCalculationResult(
            source_model="RollerBearingElement",
            application_class="RollerBearingElement",
            coefficients=(),
            scalar_kc=scalar,
            metadata=metadata,
            note="K/C calculated by ROSS RollerBearingElement analytical model.",
        )

    def _calculate_cylindrical(
        self,
        project: RotorProject,
        index: int,
        inputs: dict[str, Any],
    ) -> BearingCalculationResult:
        rs = self._ross()
        case = project.operating_cases[0]
        speed_values = inputs.get("speed_rpm")
        if speed_values is None:
            low = max(1.0, self._finite_positive(inputs.get("speed_min_rpm", max(case.speed_min_rpm, 1.0)), "Minimum speed"))
            high = self._finite_positive(inputs.get("speed_max_rpm", case.speed_max_rpm), "Maximum speed")
            if high < low:
                raise EngineeringError("Cylindrical bearing maximum speed must be >= minimum speed.")
            count = int(inputs.get("speed_points", 11))
            if count < 2:
                raise EngineeringError("Cylindrical bearing calculation requires at least two speed points.")
            speed_values = np.linspace(low, high, count)
        speeds_rpm = np.asarray(speed_values, dtype=float)
        if speeds_rpm.ndim != 1 or speeds_rpm.size < 1 or not np.all(np.isfinite(speeds_rpm)):
            raise EngineeringError("Cylindrical bearing speed vector must be a finite one-dimensional array.")
        if np.any(speeds_rpm <= 0.0) or np.any(np.diff(speeds_rpm) <= 0.0):
            raise EngineeringError("Cylindrical bearing speeds must be positive and strictly increasing.")

        weight_n = self._finite_positive(inputs.get("weight_n", 500.0), "Bearing load/weight")
        bearing_length_m = self._finite_positive(inputs.get("bearing_length_m", 0.08), "Bearing length")
        journal_diameter_m = self._finite_positive(inputs.get("journal_diameter_m", 0.10), "Journal diameter")
        radial_clearance_m = self._finite_positive(inputs.get("radial_clearance_m", 1.0e-4), "Radial clearance")
        oil_viscosity_pa_s = self._finite_positive(inputs.get("oil_viscosity_pa_s", 0.03), "Oil dynamic viscosity")
        speed_rad_s = speeds_rpm * 2.0 * pi / 60.0

        element = rs.CylindricalBearing(
            n=0,
            speed=speed_rad_s,
            weight=weight_n,
            bearing_length=bearing_length_m,
            journal_diameter=journal_diameter_m,
            radial_clearance=radial_clearance_m,
            oil_viscosity=oil_viscosity_pa_s,
        )
        points = tuple(
            self._point(rpm, self._matrix_kc(element, omega))
            for rpm, omega in zip(speeds_rpm, speed_rad_s)
        )
        rated_index = int(np.argmin(np.abs(speeds_rpm - float(case.rated_speed_rpm))))
        scalar = (
            points[rated_index].kxx, points[rated_index].kxy, points[rated_index].kyx, points[rated_index].kyy,
            points[rated_index].cxx, points[rated_index].cxy, points[rated_index].cyx, points[rated_index].cyy,
        )

        has_flexible_support = any(support.bearing_index == index for support in project.supports)
        application_class = "BearingElement" if has_flexible_support else "CylindricalBearing"
        note = (
            "ROSS CylindricalBearing calculated the hydrodynamic K/C table; the table is applied through BearingElement "
            "because ROSS 2.3 CylindricalBearing has no n_link for the project's flexible support."
            if has_flexible_support
            else "K/C calculated and applied through ROSS CylindricalBearing."
        )
        metadata: dict[str, float | int | str | list[float]] = {
            "source_model": "CylindricalBearing",
            "application_class": application_class,
            "speed_rpm": [float(value) for value in speeds_rpm],
            "weight_n": weight_n,
            "bearing_length_m": bearing_length_m,
            "journal_diameter_m": journal_diameter_m,
            "radial_clearance_m": radial_clearance_m,
            "oil_viscosity_pa_s": oil_viscosity_pa_s,
            "flexible_support_kc_adapter": int(has_flexible_support),
        }
        return BearingCalculationResult(
            source_model="CylindricalBearing",
            application_class=application_class,
            coefficients=points,
            scalar_kc=scalar,
            metadata=metadata,
            note=note,
        )

    def _calculate_magnetic(self, project: RotorProject, inputs: dict[str, Any]) -> BearingCalculationResult:
        rs = self._ross()
        speeds_rpm = np.asarray(inputs.get("speed_rpm", [project.operating_cases[0].rated_speed_rpm]), dtype=float)
        if speeds_rpm.ndim != 1 or speeds_rpm.size == 0 or np.any(speeds_rpm <= 0) or np.any(np.diff(speeds_rpm) <= 0):
            raise EngineeringError("AMB speed_rpm must be positive and strictly increasing.")
        required_positive = ("g0_m", "i0_a", "ag_m2", "nw")
        for key in required_positive:
            self._finite_positive(inputs.get(key), key)
        frequency = speeds_rpm * 2.0 * pi / 60.0
        element = rs.MagneticBearingElement(
            n=0, g0=float(inputs["g0_m"]), i0=float(inputs["i0_a"]), ag=float(inputs["ag_m2"]), nw=float(inputs["nw"]),
            frequency=frequency, alpha=float(inputs.get("alpha_rad", pi / 8.0)),
            k_amp=float(inputs.get("k_amp", 1.0)), k_sense=float(inputs.get("k_sense", 1.0)),
            kp_pid=float(inputs.get("kp_pid", 0.0)), kd_pid=float(inputs.get("kd_pid", 0.0)), ki_pid=float(inputs.get("ki_pid", 0.0)),
            n_f=float(inputs.get("n_f_rad_s", 10000.0)), sensors_axis_rotation=float(inputs.get("sensors_axis_rotation_rad", pi / 4.0)),
        )
        points = tuple(self._point(rpm, self._matrix_kc(element, omega)) for rpm, omega in zip(speeds_rpm, frequency))
        rated = min(points, key=lambda point: abs(point.rpm - project.operating_cases[0].rated_speed_rpm))
        scalar = (rated.kxx, rated.kxy, rated.kyx, rated.kyy, rated.cxx, rated.cxy, rated.cyx, rated.cyy)
        engineering_input = {key: value for key, value in inputs.items()}
        engineering_input["speed_rpm"] = [float(value) for value in speeds_rpm]
        return BearingCalculationResult(
            source_model="MagneticBearingElement", application_class="MagneticBearingElement",
            coefficients=points, scalar_kc=scalar,
            metadata={"source_model": "MagneticBearingElement", "engineering_input": engineering_input},
            note="Native ROSS MagneticBearingElement electromagnetic/PID model; Newmark is mandatory for active time-domain feedback.",
        )

    def apply(self, project: RotorProject, index: int, result: BearingCalculationResult) -> BearingSpec:
        spec = self._bearing(project, index)
        kxx, kxy, kyx, kyy, cxx, cxy, cyx, cyy = result.scalar_kc
        spec.ross_class = result.application_class
        spec.group = BearingGroup.AMB if result.source_model == "MagneticBearingElement" else BearingGroup.GENERAL
        spec.kxx = kxx
        spec.kxy = kxy
        spec.kyx = kyx
        spec.kyy = kyy
        spec.cxx = cxx
        spec.cxy = cxy
        spec.cyx = cyx
        spec.cyy = cyy
        spec.coefficients = list(result.coefficients)
        spec.metadata = dict(result.metadata)
        project.validate()
        return spec


__all__ = ["BearingCalculationResult", "BearingStudioService"]
