from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
import hashlib
from importlib import import_module
import json
from math import pi
from typing import Any, Mapping
import warnings

import numpy as np

from .domain import BearingCoefficientPoint, EngineeringError, RotorProject, SealModel, SealSpec


_COEFFICIENT_KEYS = ("kxx", "kxy", "kyx", "kyy", "cxx", "cxy", "cyx", "cyy")


@dataclass(slots=True)
class SealCalculationResult:
    """Traceable preview generated by a validated native ROSS 2.3.0 seal model."""

    source_model: SealModel
    native_element: Any
    applied_spec: SealSpec
    coefficients: tuple[BearingCoefficientPoint, ...]
    leakage_kg_s: tuple[float, ...]
    interface_pressure_pa: float | None = None
    iterations: int | None = None
    residual: float | None = None
    fluid_backend: dict[str, object] | None = None
    native_warnings: tuple[str, ...] = ()
    input_fingerprint: str = ""
    note: str = ""


class SealStudioService:
    """Native ROSS seal calculation/reconstruction boundary.

    The Studio never reimplements LabyrinthSeal/HolePatternSeal/HybridSeal physics.
    Engineering inputs are normalized and converted only at the native ROSS 2.3.0
    constructor boundary. All iterative models are validated after construction so a
    returned object is not automatically treated as a converged scientific result.
    """

    def __init__(self, ross_module: Any | None = None) -> None:
        self.rs = ross_module

    def _ross(self) -> Any:
        if self.rs is None:
            self.rs = import_module("ross")
        return self.rs

    @staticmethod
    def _class(module: str, name: str) -> type[Any]:
        return getattr(import_module(module), name)

    @staticmethod
    def _finite(
        value: Any,
        label: str,
        *,
        positive: bool = False,
        nonnegative: bool = False,
    ) -> float:
        try:
            number = float(value)
        except (TypeError, ValueError) as exc:
            raise EngineeringError(
                f"{label}={value!r}; expected a finite physical numeric value. "
                "Correct the field before Calculate."
            ) from exc
        if not np.isfinite(number):
            raise EngineeringError(
                f"{label}={value!r}; expected a finite physical value. "
                "NaN/Infinity cannot define a seal model. Correct the field before Calculate."
            )
        if positive and number <= 0:
            raise EngineeringError(
                f"{label}={number:g}; expected > 0. A zero/negative value is nonphysical for this seal input. "
                "Enter a positive value."
            )
        if nonnegative and number < 0:
            raise EngineeringError(
                f"{label}={number:g}; expected >= 0. A negative value is nonphysical for this seal input. "
                "Enter a non-negative value."
            )
        return number

    @classmethod
    def _positive_int(cls, value: Any, label: str, *, minimum: int = 1, maximum: int | None = None) -> int:
        try:
            number = int(value)
        except (TypeError, ValueError) as exc:
            raise EngineeringError(
                f"{label}={value!r}; expected an integer >= {minimum}. Correct the field before Calculate."
            ) from exc
        if number < minimum or (maximum is not None and number > maximum):
            upper = "" if maximum is None else f" and <= {maximum}"
            raise EngineeringError(
                f"{label}={number}; expected >= {minimum}{upper}. "
                "The requested discretization/iteration count is outside the supported physical/numerical contract."
            )
        return number

    @classmethod
    def _speed_rpm(cls, values: Any) -> np.ndarray:
        try:
            speed = np.asarray(values, dtype=float)
        except (TypeError, ValueError) as exc:
            raise EngineeringError(
                f"frequency_rpm={values!r}; expected a one-dimensional numeric vector in rpm."
            ) from exc
        if speed.ndim != 1 or speed.size == 0 or not np.all(np.isfinite(speed)):
            raise EngineeringError(
                f"frequency_rpm={values!r}; expected a finite one-dimensional vector in rpm. "
                "Remove NaN/Infinity and provide at least one speed."
            )
        if np.any(speed <= 0) or (speed.size > 1 and np.any(np.diff(speed) <= 0)):
            raise EngineeringError(
                f"frequency_rpm={speed.tolist()!r}; expected positive, strictly increasing rpm values. "
                "Sort rows, remove duplicates and remove zero/negative speeds."
            )
        return speed

    @staticmethod
    def _gas(value: Any) -> dict[str, float] | None:
        if value in (None, "", {}):
            return None
        if not isinstance(value, Mapping):
            raise EngineeringError(
                f"gas_composition={value!r}; expected a mapping of species to positive mole fractions. "
                "Provide a fluid composition dictionary."
            )
        result = {str(key): float(item) for key, item in value.items()}
        if not result or any(not np.isfinite(item) or item <= 0 for item in result.values()):
            raise EngineeringError(
                f"gas_composition={result!r}; expected positive finite mole fractions. "
                "Correct invalid components before Calculate."
            )
        total = sum(result.values())
        if not np.isfinite(total) or total <= 0:
            raise EngineeringError(
                f"gas_composition total={total!r}; expected a positive finite total mole fraction."
            )
        return result

    @staticmethod
    def _coefficient_vector(value: Any, label: str, size: int) -> list[float]:
        if isinstance(value, (list, tuple, np.ndarray)):
            vector = np.asarray(value, dtype=float)
            if vector.ndim != 1 or vector.size != size or not np.all(np.isfinite(vector)):
                raise EngineeringError(
                    f"{label}={value!r}; expected {size} finite rows matching frequency_rpm. "
                    "Correct the coefficient table so every K/C column has the same row count."
                )
            return [float(item) for item in vector]
        number = float(value)
        if not np.isfinite(number):
            raise EngineeringError(
                f"{label}={value!r}; expected a finite K/C coefficient. Correct NaN/Infinity before Calculate."
            )
        return [number] * size

    @staticmethod
    def _matrix_point(element: Any, rpm: float) -> BearingCoefficientPoint:
        omega = float(rpm) * 2.0 * pi / 60.0
        k = np.asarray(element.K(omega), dtype=float)
        c = np.asarray(element.C(omega), dtype=float)
        if k.shape[0] < 2 or c.shape[0] < 2:
            raise EngineeringError(
                f"ROSS seal returned K{tuple(k.shape)} and C{tuple(c.shape)}; expected at least a lateral 2x2 block."
            )
        values = (k[0, 0], k[0, 1], k[1, 0], k[1, 1], c[0, 0], c[0, 1], c[1, 0], c[1, 1])
        if not all(np.isfinite(float(value)) for value in values):
            raise EngineeringError(
                f"ROSS seal returned non-finite K/C at {rpm:g} rpm; expected finite native coefficients. "
                "Check fluid state, geometry, pressure drop and numerical convergence."
            )
        return BearingCoefficientPoint(
            rpm=float(rpm),
            kxx=float(k[0, 0]),
            kxy=float(k[0, 1]),
            kyx=float(k[1, 0]),
            kyy=float(k[1, 1]),
            cxx=float(c[0, 0]),
            cxy=float(c[0, 1]),
            cyx=float(c[1, 0]),
            cyy=float(c[1, 1]),
        )

    @staticmethod
    def _leakage(element: Any, count: int) -> tuple[float, ...]:
        raw = getattr(element, "seal_leakage", ())
        if raw is None:
            return ()
        values = np.atleast_1d(raw).astype(float)
        if values.size == 1 and count > 1:
            values = np.repeat(values, count)
        if not np.all(np.isfinite(values)):
            raise EngineeringError(
                f"ROSS seal leakage={values.tolist()!r}; expected finite mass flow. "
                "The native solve is invalid and cannot be applied."
            )
        return tuple(float(item) for item in values)

    @staticmethod
    def _engineering_fingerprint(model: SealModel, normalized: Mapping[str, Any]) -> str:
        payload = json.dumps(
            {"model": model.value, "inputs": normalized},
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        )
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()

    def input_fingerprint(
        self,
        project: RotorProject,
        index: int,
        model: SealModel | str,
        inputs: Mapping[str, Any],
    ) -> str:
        if not 0 <= int(index) < len(project.seals):
            raise EngineeringError(f"Seal index {index} is outside the project seal range.")
        model = model if isinstance(model, SealModel) else SealModel(str(model))
        normalized = self.normalize_inputs(project, project.seals[int(index)], model, inputs)
        return self._engineering_fingerprint(model, normalized)

    @staticmethod
    def _thermodynamic_backend_evidence(
        normalized: Mapping[str, Any],
    ) -> dict[str, object]:
        ccp = import_module("ccp")
        configured = str(getattr(ccp.config, "EOS", "UNKNOWN"))
        refprop_available = bool(getattr(ccp, "REFPROP_AVAILABLE", False))
        pin = float(normalized["inlet_pressure_bar"]) * 1.0e5
        tin = float(normalized["inlet_temperature_c"]) + 273.15
        fluid = normalized.get("gas_composition")
        state = ccp.State(p=pin, T=tin, fluid=fluid)
        raw_backend = ""
        backend_name = getattr(state, "backend_name", None)
        if callable(backend_name):
            try:
                raw_backend = str(backend_name())
            except Exception:
                raw_backend = ""
        if configured.upper() == "HEOS":
            effective = "HEOS/CoolProp"
        elif configured.upper() == "REFPROP":
            effective = "REFPROP"
        else:
            effective = raw_backend or configured
        fallback = bool(not refprop_available and configured.upper() == "HEOS")
        warning = (
            "REFPROP unavailable; upstream ccp selected EOS='HEOS' (CoolProp backend). "
            "This is an explicit thermodynamic-backend fallback, not REFPROP equivalence."
            if fallback
            else ""
        )
        return {
            "requested_eos": "REFPROP (ccp upstream default)",
            "configured_eos": configured,
            "actual_backend": effective,
            "actual_backend_raw": raw_backend,
            "refprop_available": refprop_available,
            "fallback_occurred": fallback,
            "fluid": deepcopy(fluid),
            "state": {"pressure_pa": pin, "temperature_k": tin},
            "warning": warning,
            "status": "FALLBACK_VISIBLE" if fallback else "REQUESTED_BACKEND",
        }

    def normalize_inputs(
        self,
        project: RotorProject,
        spec: SealSpec,
        model: SealModel,
        inputs: Mapping[str, Any],
    ) -> dict[str, Any]:
        raw = dict(inputs)
        if model is SealModel.DIRECT:
            frequency_value = raw.get("frequency_rpm")
            has_frequency = frequency_value is not None and frequency_value != ""
            if isinstance(frequency_value, (list, tuple, np.ndarray)) and len(frequency_value) == 0:
                has_frequency = False
            if has_frequency:
                speed = self._speed_rpm(frequency_value)
                normalized: dict[str, Any] = {"frequency_rpm": [float(item) for item in speed]}
                for key in _COEFFICIENT_KEYS:
                    normalized[key] = self._coefficient_vector(
                        raw.get(key, getattr(spec, key)),
                        key,
                        speed.size,
                    )
                return normalized
            normalized = {}
            for key in _COEFFICIENT_KEYS:
                normalized[key] = self._finite(raw.get(key, getattr(spec, key)), key)
            return normalized

        case = project.operating_cases[0]
        speed = self._speed_rpm(raw.get("frequency_rpm", [max(1.0, case.rated_speed_rpm)]))

        def pressure_bar(prefix: str, default_bar: float) -> float:
            bar_key = f"{prefix}_pressure_bar"
            pa_key = f"{prefix}_pressure_pa"
            if bar_key in raw:
                return self._finite(raw[bar_key], bar_key, nonnegative=(prefix == "outlet"), positive=(prefix == "inlet"))
            if pa_key in raw:
                pa = self._finite(raw[pa_key], pa_key, nonnegative=(prefix == "outlet"), positive=(prefix == "inlet"))
                return pa / 1.0e5
            return default_bar

        if "inlet_temperature_c" in raw:
            temp_c = self._finite(raw["inlet_temperature_c"], "inlet_temperature_c")
        elif "inlet_temperature_k" in raw:
            temp_k = self._finite(raw["inlet_temperature_k"], "inlet_temperature_k", positive=True)
            temp_c = temp_k - 273.15
        else:
            temp_c = 26.85
        if temp_c <= -273.15:
            raise EngineeringError(
                f"inlet_temperature_c={temp_c:g}; expected absolute temperature > 0 K (> -273.15 °C). "
                "Correct the thermodynamic state."
            )

        common: dict[str, Any] = {
            "shaft_diameter_mm": self._finite(
                raw.get("shaft_diameter_mm", 100.0), "shaft_diameter_mm", positive=True
            ),
            "inlet_pressure_bar": pressure_bar("inlet", 5.0),
            "outlet_pressure_bar": pressure_bar("outlet", 1.0),
            "inlet_temperature_c": temp_c,
            "frequency_rpm": [float(value) for value in speed],
            "gas_composition": self._gas(
                raw.get(
                    "gas_composition",
                    {"Nitrogen": 0.7812, "Oxygen": 0.2096, "Argon": 0.0092},
                )
            ),
        }
        if common["outlet_pressure_bar"] >= common["inlet_pressure_bar"]:
            raise EngineeringError(
                f"inlet_pressure_bar={common['inlet_pressure_bar']:g}, "
                f"outlet_pressure_bar={common['outlet_pressure_bar']:g}; expected inlet > outlet. "
                "The compressible seal requires a positive pressure drop. Correct the pressure ordering."
            )

        if model is SealModel.LABYRINTH:
            common.update(
                {
                    "radial_clearance_mm": self._finite(
                        raw.get("radial_clearance_mm", 0.3), "radial_clearance_mm", positive=True
                    ),
                    "n_teeth": self._positive_int(raw.get("n_teeth", 10), "n_teeth", minimum=2, maximum=30),
                    "pitch_mm": self._finite(raw.get("pitch_mm", 3.0), "pitch_mm", positive=True),
                    "tooth_height_mm": self._finite(
                        raw.get("tooth_height_mm", 3.0), "tooth_height_mm", positive=True
                    ),
                    "tooth_width_mm": self._finite(
                        raw.get("tooth_width_mm", 0.15), "tooth_width_mm", positive=True
                    ),
                    "seal_type": str(raw.get("seal_type", "inter")),
                    "preswirl": self._finite(raw.get("preswirl", 0.8), "preswirl"),
                    "use_jenny_kanki": bool(raw.get("use_jenny_kanki", False)),
                }
            )
            if common["seal_type"] not in {"inter", "rotor", "stator"}:
                raise EngineeringError(
                    f"seal_type={common['seal_type']!r}; expected 'inter', 'rotor' or 'stator'. "
                    "Choose a ROSS 2.3.0 labyrinth type."
                )
            return common

        if model is SealModel.HOLE_PATTERN:
            first_step = self._finite(raw.get("first_step_size", 0.01), "first_step_size", positive=True)
            relaxation = self._finite(raw.get("relaxation_factor", 0.1), "relaxation_factor", positive=True)
            if first_step > 0.01:
                raise EngineeringError(
                    f"first_step_size={first_step:g}; expected <= 0.01 per ROSS 2.3.0 HolePatternSeal. "
                    "Reduce the initial step."
                )
            if relaxation > 0.1:
                raise EngineeringError(
                    f"relaxation_factor={relaxation:g}; expected <= 0.1 per ROSS 2.3.0 HolePatternSeal. "
                    "Reduce the relaxation factor."
                )
            common.update(
                {
                    "radial_clearance_mm": self._finite(
                        raw.get("radial_clearance_mm", 0.18), "radial_clearance_mm", positive=True
                    ),
                    "axial_length_mm": self._finite(
                        raw.get("axial_length_mm", 84.9), "axial_length_mm", positive=True
                    ),
                    "relative_roughness": self._finite(
                        raw.get("relative_roughness", 1e-4), "relative_roughness", nonnegative=True
                    ),
                    "cell_length_mm": self._finite(
                        raw.get("cell_length_mm", 2.3), "cell_length_mm", positive=True
                    ),
                    "cell_width_mm": self._finite(
                        raw.get("cell_width_mm", 2.1), "cell_width_mm", positive=True
                    ),
                    "cell_depth_mm": self._finite(
                        raw.get("cell_depth_mm", 2.8), "cell_depth_mm", positive=True
                    ),
                    "preswirl": self._finite(raw.get("preswirl", 1.0), "preswirl"),
                    "entrance_loss_coefficient": self._finite(
                        raw.get("entrance_loss_coefficient", 0.1),
                        "entrance_loss_coefficient",
                        nonnegative=True,
                    ),
                    "exit_loss_coefficient": self._finite(
                        raw.get("exit_loss_coefficient", 0.5),
                        "exit_loss_coefficient",
                        nonnegative=True,
                    ),
                    "excitation_ratio": self._finite(
                        raw.get("excitation_ratio", 1.0), "excitation_ratio", positive=True
                    ),
                    "nz": self._positive_int(raw.get("nz", 40), "nz"),
                    "max_iterations": self._positive_int(
                        raw.get("max_iterations", 180), "max_iterations"
                    ),
                    "tolerance": self._finite(raw.get("tolerance", 1e-4), "tolerance", positive=True),
                    "first_step_size": first_step,
                    "relaxation_factor": relaxation,
                }
            )
            return common

        hole_first_step = self._finite(
            raw.get("hole_first_step_size", 0.01), "hole_first_step_size", positive=True
        )
        hole_relax = self._finite(
            raw.get("hole_relaxation_factor", 0.1), "hole_relaxation_factor", positive=True
        )
        if hole_first_step > 0.01:
            raise EngineeringError(
                f"hole_first_step_size={hole_first_step:g}; expected <= 0.01. Reduce the hybrid hole-pattern initial step."
            )
        if hole_relax > 0.1:
            raise EngineeringError(
                f"hole_relaxation_factor={hole_relax:g}; expected <= 0.1. Reduce the hybrid hole-pattern relaxation."
            )
        common.update(
            {
                "hole_radial_clearance_mm": self._finite(
                    raw.get("hole_radial_clearance_mm", 0.30), "hole_radial_clearance_mm", positive=True
                ),
                "hole_axial_length_mm": self._finite(
                    raw.get("hole_axial_length_mm", 40.0), "hole_axial_length_mm", positive=True
                ),
                "hole_relative_roughness": self._finite(
                    raw.get("hole_relative_roughness", 1e-4), "hole_relative_roughness", nonnegative=True
                ),
                "hole_cell_length_mm": self._finite(
                    raw.get("hole_cell_length_mm", 3.0), "hole_cell_length_mm", positive=True
                ),
                "hole_cell_width_mm": self._finite(
                    raw.get("hole_cell_width_mm", 3.0), "hole_cell_width_mm", positive=True
                ),
                "hole_cell_depth_mm": self._finite(
                    raw.get("hole_cell_depth_mm", 2.0), "hole_cell_depth_mm", positive=True
                ),
                "hole_preswirl": self._finite(raw.get("hole_preswirl", 0.8), "hole_preswirl"),
                "hole_entrance_loss_coefficient": self._finite(
                    raw.get("hole_entrance_loss_coefficient", 0.5),
                    "hole_entrance_loss_coefficient",
                    nonnegative=True,
                ),
                "hole_exit_loss_coefficient": self._finite(
                    raw.get("hole_exit_loss_coefficient", 1.0),
                    "hole_exit_loss_coefficient",
                    nonnegative=True,
                ),
                "hole_excitation_ratio": self._finite(
                    raw.get("hole_excitation_ratio", 1.0), "hole_excitation_ratio", positive=True
                ),
                "hole_nz": self._positive_int(raw.get("hole_nz", 18), "hole_nz"),
                "hole_max_iterations": self._positive_int(
                    raw.get("hole_max_iterations", 180), "hole_max_iterations"
                ),
                "hole_tolerance": self._finite(
                    raw.get("hole_tolerance", 1e-4), "hole_tolerance", positive=True
                ),
                "hole_first_step_size": hole_first_step,
                "hole_relaxation_factor": hole_relax,
                "lab_radial_clearance_mm": self._finite(
                    raw.get("lab_radial_clearance_mm", 0.25), "lab_radial_clearance_mm", positive=True
                ),
                "lab_n_teeth": self._positive_int(
                    raw.get("lab_n_teeth", 10), "lab_n_teeth", minimum=2, maximum=30
                ),
                "lab_pitch_mm": self._finite(
                    raw.get("lab_pitch_mm", 3.0), "lab_pitch_mm", positive=True
                ),
                "lab_tooth_height_mm": self._finite(
                    raw.get("lab_tooth_height_mm", 3.0), "lab_tooth_height_mm", positive=True
                ),
                "lab_tooth_width_mm": self._finite(
                    raw.get("lab_tooth_width_mm", 0.15), "lab_tooth_width_mm", positive=True
                ),
                "lab_seal_type": str(raw.get("lab_seal_type", "inter")),
                "lab_preswirl": self._finite(raw.get("lab_preswirl", 0.9), "lab_preswirl"),
                "tolerance": self._finite(raw.get("tolerance", 1e-6), "tolerance", positive=True),
                "max_iterations": self._positive_int(raw.get("max_iterations", 100), "max_iterations"),
            }
        )
        if common["lab_seal_type"] not in {"inter", "rotor", "stator"}:
            raise EngineeringError(
                f"lab_seal_type={common['lab_seal_type']!r}; expected 'inter', 'rotor' or 'stator'. "
                "Choose a ROSS 2.3.0 labyrinth type."
            )
        return common

    def _construct_native(
        self,
        spec: SealSpec,
        model: SealModel,
        value: Mapping[str, Any],
        *,
        node: int,
    ) -> Any:
        rs = self._ross()
        if model is SealModel.DIRECT:
            if "frequency_rpm" in value:
                frequency = np.asarray(value["frequency_rpm"], dtype=float) * 2.0 * pi / 60.0
                arrays = {key: np.asarray(value[key], dtype=float) for key in _COEFFICIENT_KEYS}
                return rs.SealElement(
                    n=node,
                    tag=spec.name,
                    frequency=frequency,
                    kxx=arrays["kxx"],
                    kyy=arrays["kyy"],
                    kxy=arrays["kxy"],
                    kyx=arrays["kyx"],
                    cxx=arrays["cxx"],
                    cyy=arrays["cyy"],
                    cxy=arrays["cxy"],
                    cyx=arrays["cyx"],
                )
            return rs.SealElement(
                n=node,
                tag=spec.name,
                kxx=float(value["kxx"]),
                kyy=float(value["kyy"]),
                kxy=float(value["kxy"]),
                kyx=float(value["kyx"]),
                cxx=float(value["cxx"]),
                cyy=float(value["cyy"]),
                cxy=float(value["cxy"]),
                cyx=float(value["cyx"]),
            )

        frequency = np.asarray(value["frequency_rpm"], dtype=float) * 2.0 * pi / 60.0
        common = dict(
            n=node,
            shaft_radius=float(value["shaft_diameter_mm"]) / 2000.0,
            inlet_pressure=float(value["inlet_pressure_bar"]) * 1.0e5,
            outlet_pressure=float(value["outlet_pressure_bar"]) * 1.0e5,
            inlet_temperature=float(value["inlet_temperature_c"]) + 273.15,
            frequency=frequency,
            gas_composition=value.get("gas_composition"),
            tag=spec.name,
        )
        if model is SealModel.LABYRINTH:
            cls = self._class("ross.seals.labyrinth_seal", "LabyrinthSeal")
            return cls(
                **common,
                radial_clearance=float(value["radial_clearance_mm"]) / 1000.0,
                n_teeth=int(value["n_teeth"]),
                pitch=float(value["pitch_mm"]) / 1000.0,
                tooth_height=float(value["tooth_height_mm"]) / 1000.0,
                tooth_width=float(value["tooth_width_mm"]) / 1000.0,
                seal_type=str(value["seal_type"]),
                preswirl=float(value["preswirl"]),
                iopt1=int(bool(value.get("use_jenny_kanki", False))),
            )

        if model is SealModel.HOLE_PATTERN:
            cls = self._class("ross.seals.holepattern_seal", "HolePatternSeal")
            return cls(
                **common,
                radial_clearance=float(value["radial_clearance_mm"]) / 1000.0,
                length=float(value["axial_length_mm"]) / 1000.0,
                roughness=float(value["relative_roughness"]),
                cell_length=float(value["cell_length_mm"]) / 1000.0,
                cell_width=float(value["cell_width_mm"]) / 1000.0,
                cell_depth=float(value["cell_depth_mm"]) / 1000.0,
                preswirl=float(value["preswirl"]),
                entr_coef=float(value["entrance_loss_coefficient"]),
                exit_coef=float(value["exit_loss_coefficient"]),
                whirl_ratio=float(value["excitation_ratio"]),
                nz=int(value["nz"]),
                max_iterations=int(value["max_iterations"]),
                tolerance=float(value["tolerance"]),
                first_step_size=float(value["first_step_size"]),
                rlx_factor=float(value["relaxation_factor"]),
            )

        cls = self._class("ross.seals.hybrid_seal", "HybridSeal")
        hole = {
            "radial_clearance": float(value["hole_radial_clearance_mm"]) / 1000.0,
            "length": float(value["hole_axial_length_mm"]) / 1000.0,
            "roughness": float(value["hole_relative_roughness"]),
            "cell_length": float(value["hole_cell_length_mm"]) / 1000.0,
            "cell_width": float(value["hole_cell_width_mm"]) / 1000.0,
            "cell_depth": float(value["hole_cell_depth_mm"]) / 1000.0,
            "preswirl": float(value["hole_preswirl"]),
            "entr_coef": float(value["hole_entrance_loss_coefficient"]),
            "exit_coef": float(value["hole_exit_loss_coefficient"]),
            "whirl_ratio": float(value["hole_excitation_ratio"]),
            "nz": int(value["hole_nz"]),
            "max_iterations": int(value["hole_max_iterations"]),
            "tolerance": float(value["hole_tolerance"]),
            "first_step_size": float(value["hole_first_step_size"]),
            "rlx_factor": float(value["hole_relaxation_factor"]),
        }
        lab = {
            "radial_clearance": float(value["lab_radial_clearance_mm"]) / 1000.0,
            "n_teeth": int(value["lab_n_teeth"]),
            "pitch": float(value["lab_pitch_mm"]) / 1000.0,
            "tooth_height": float(value["lab_tooth_height_mm"]) / 1000.0,
            "tooth_width": float(value["lab_tooth_width_mm"]) / 1000.0,
            "seal_type": str(value["lab_seal_type"]),
            "preswirl": float(value["lab_preswirl"]),
        }
        return cls(
            **common,
            hole_pattern_parameters=hole,
            labyrinth_parameters=lab,
            tolerance=float(value["tolerance"]),
            max_iterations=int(value["max_iterations"]),
        )

    @staticmethod
    def _all_zero_lateral_coefficients(element: Any, speed_rpm: list[float]) -> bool:
        values: list[float] = []
        for rpm in speed_rpm:
            omega = float(rpm) * 2.0 * pi / 60.0
            k = np.asarray(element.K(omega), dtype=float)
            c = np.asarray(element.C(omega), dtype=float)
            values.extend([k[0, 0], k[0, 1], k[1, 0], k[1, 1], c[0, 0], c[0, 1], c[1, 0], c[1, 1]])
        return bool(values and np.all(np.asarray(values, dtype=float) == 0.0))

    def _validate_native(
        self,
        spec: SealSpec,
        model: SealModel,
        value: Mapping[str, Any],
        native: Any,
        warning_messages: tuple[str, ...],
    ) -> None:
        speeds = [float(item) for item in value.get("frequency_rpm", [])]
        for rpm in speeds or [1.0]:
            self._matrix_point(native, rpm)

        if model is SealModel.DIRECT:
            return

        error_warnings = [
            message for message in warning_messages
            if "error calculating for frequency" in message.casefold()
        ]
        if error_warnings:
            raise EngineeringError(
                f"{model.value} seal {spec.name!r} emitted an upstream scientific-failure warning: "
                f"{' | '.join(error_warnings)}. ROSS 2.3.0 may replace this failure with zero coefficients; "
                "ROSS Studio rejects that fallback and will not mark the preview Ready."
            )

        leakage = self._leakage(native, max(1, len(speeds)))
        if leakage and (not all(np.isfinite(item) for item in leakage) or any(item <= 0.0 for item in leakage)):
            raise EngineeringError(
                f"{model.value} seal {spec.name!r} returned leakage={leakage!r}; expected finite positive mass flow "
                "for positive pressure drop. The native solution is not scientifically valid."
            )

        if self._all_zero_lateral_coefficients(native, speeds):
            raise EngineeringError(
                f"{model.value} seal {spec.name!r} returned an all-zero lateral K/C solution at positive speed "
                "and positive pressure drop. This matches the ROSS 2.3.0 failure fallback signature and is rejected. "
                "Correct geometry/fluid/numerical inputs and recalculate."
            )

        if model is SealModel.HOLE_PATTERN:
            pressure_rows = getattr(native, "p", None)
            residuals: list[float] = []
            if pressure_rows is not None:
                rows = pressure_rows if isinstance(pressure_rows, (list, tuple)) else [pressure_rows]
                pin = float(value["inlet_pressure_bar"]) * 1.0e5
                pout = float(value["outlet_pressure_bar"]) * 1.0e5
                scale = abs(pin - pout)
                for row in rows:
                    array = np.asarray(row, dtype=float).ravel()
                    if array.size and np.all(np.isfinite(array)):
                        residuals.append(abs(float(array[-1]) - pout) / scale)
            if residuals:
                residual = max(residuals)
                tolerance = float(value["tolerance"])
                if not np.isfinite(residual) or residual > tolerance * (1.0 + 1.0e-9):
                    raise EngineeringError(
                        f"HolePatternSeal {spec.name!r}: outlet-pressure residual={residual:.6e}; "
                        f"expected <= requested tolerance={tolerance:.6e}. "
                        "The base-state pressure solve did not satisfy the requested tolerance; result rejected."
                    )

        if model is SealModel.HYBRID:
            history = list(getattr(native, "convergence_history", ()) or ())
            if not history:
                raise EngineeringError(
                    f"HybridSeal {spec.name!r}: convergence_history is empty; expected a finite mass-flow matching history. "
                    "The result cannot be treated as converged."
                )
            residual = float(history[-1])
            tolerance = float(value["tolerance"])
            iterations = int(getattr(native, "n_iterations", len(history)))
            lab_hist = np.asarray(getattr(native, "leakage_laby_history", ()), dtype=float)
            hole_hist = np.asarray(getattr(native, "leakage_hole_history", ()), dtype=float)
            coherent = (
                len(history) == iterations
                and lab_hist.size == iterations
                and hole_hist.size == iterations
                and np.all(np.isfinite(np.asarray(history, dtype=float)))
                and np.all(np.isfinite(lab_hist))
                and np.all(np.isfinite(hole_hist))
            )
            if not coherent:
                raise EngineeringError(
                    f"HybridSeal {spec.name!r}: convergence history/iteration bookkeeping is inconsistent; "
                    f"history={len(history)}, lab={lab_hist.size}, hole={hole_hist.size}, iterations={iterations}. "
                    "Result rejected."
                )
            last_hole = float(hole_hist[-1])
            last_lab = float(lab_hist[-1])
            mass_residual = abs(last_lab - last_hole) / abs(last_hole) if last_hole != 0.0 else float("inf")
            if (
                not np.isfinite(residual)
                or not np.isfinite(mass_residual)
                or residual > tolerance
                or mass_residual > tolerance
                or iterations > int(value["max_iterations"])
                or abs(residual - mass_residual) > max(1.0e-12, tolerance * 1.0e-6)
            ):
                raise EngineeringError(
                    f"HybridSeal {spec.name!r}: residual={residual:.6e}, independent mass-flow residual={mass_residual:.6e}, "
                    f"requested tolerance={tolerance:.6e}, iterations={iterations}, "
                    f"max_iterations={int(value['max_iterations'])}. Expected finite residual <= tolerance and consistent "
                    "mass flow. The two stages did not converge; result rejected and Apply remains unavailable."
                )

    def native_from_inputs(
        self,
        spec: SealSpec,
        model: SealModel,
        values: Mapping[str, Any],
        *,
        node: int,
    ) -> Any:
        value = dict(values)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            native = self._construct_native(spec, model, value, node=node)
        warning_messages = tuple(str(item.message) for item in caught)
        self._validate_native(spec, model, value, native, warning_messages)
        setattr(native, "_ross_studio_native_warnings", warning_messages)
        return native

    def calculate(
        self,
        project: RotorProject,
        index: int,
        model: SealModel | str,
        inputs: Mapping[str, Any],
    ) -> SealCalculationResult:
        if not 0 <= int(index) < len(project.seals):
            raise EngineeringError(f"Seal index {index} is outside the project seal range.")
        source = project.seals[int(index)]
        model = model if isinstance(model, SealModel) else SealModel(str(model))
        normalized = self.normalize_inputs(project, source, model, inputs)
        fingerprint = self._engineering_fingerprint(model, normalized)
        native = self.native_from_inputs(source, model, normalized, node=0)
        warning_messages = tuple(getattr(native, "_ross_studio_native_warnings", ()))

        speeds = normalized.get("frequency_rpm")
        if speeds is None:
            speeds = [float(project.operating_cases[0].rated_speed_rpm)]
        points = tuple(self._matrix_point(native, float(rpm)) for rpm in speeds)
        nominal = min(
            points,
            key=lambda point: abs(point.rpm - project.operating_cases[0].rated_speed_rpm),
        )

        backend = None
        if model is not SealModel.DIRECT:
            backend = self._thermodynamic_backend_evidence(normalized)

        residual = None
        if model is SealModel.HYBRID:
            history = list(getattr(native, "convergence_history", ()) or ())
            residual = None if not history else float(history[-1])
        elif model is SealModel.HOLE_PATTERN:
            pressure_rows = getattr(native, "p", None)
            if pressure_rows is not None:
                rows = pressure_rows if isinstance(pressure_rows, (list, tuple)) else [pressure_rows]
                pin = float(normalized["inlet_pressure_bar"]) * 1.0e5
                pout = float(normalized["outlet_pressure_bar"]) * 1.0e5
                scale = abs(pin - pout)
                values = []
                for row in rows:
                    array = np.asarray(row, dtype=float).ravel()
                    if array.size and np.all(np.isfinite(array)):
                        values.append(abs(float(array[-1]) - pout) / scale)
                if values:
                    residual = max(values)

        applied = deepcopy(source)
        applied.model = model
        applied.kxx, applied.kxy, applied.kyx, applied.kyy = (
            nominal.kxx,
            nominal.kxy,
            nominal.kyx,
            nominal.kyy,
        )
        applied.cxx, applied.cxy, applied.cyx, applied.cyy = (
            nominal.cxx,
            nominal.cxy,
            nominal.cyx,
            nominal.cyy,
        )
        applied.metadata = {
            "source_model": model.value,
            "engineering_input": deepcopy(normalized),
            "thermodynamic_backend": deepcopy(backend),
            "convergence": {
                "residual": residual,
                "iterations": getattr(native, "n_iterations", None),
                "native_warnings": list(warning_messages),
            },
        }
        interface = getattr(native, "interface_pressure", None)
        iterations = getattr(native, "n_iterations", None)
        note = {
            SealModel.DIRECT: "Native ROSS 2.3.0 SealElement direct K/C preview.",
            SealModel.LABYRINTH: "Native ROSS 2.3.0 LabyrinthSeal compressible-flow solve.",
            SealModel.HOLE_PATTERN: "Native ROSS 2.3.0 HolePatternSeal bulk-flow solve.",
            SealModel.HYBRID: "Native ROSS 2.3.0 HybridSeal mass-flow matched hole-pattern + labyrinth solve.",
        }[model]
        return SealCalculationResult(
            source_model=model,
            native_element=native,
            applied_spec=applied,
            coefficients=points,
            leakage_kg_s=self._leakage(native, len(points)),
            interface_pressure_pa=None if interface is None else float(interface),
            iterations=None if iterations is None else int(iterations),
            residual=residual,
            fluid_backend=backend,
            native_warnings=warning_messages,
            input_fingerprint=fingerprint,
            note=note,
        )

    def apply(self, project: RotorProject, index: int, result: SealCalculationResult) -> SealSpec:
        if not 0 <= int(index) < len(project.seals):
            raise EngineeringError(f"Seal index {index} is outside the project seal range.")
        project.seals[int(index)] = deepcopy(result.applied_spec)
        project.validate()
        return project.seals[int(index)]

    @staticmethod
    def _upgrade_persisted_inputs(model: SealModel, values: Mapping[str, Any]) -> dict[str, Any]:
        """Read schema-3 seal metadata written by earlier 0.30 builds without changing physics."""
        value = deepcopy(dict(values))
        if model is SealModel.DIRECT:
            return value
        if "inlet_pressure_bar" not in value and "inlet_pressure_pa" in value:
            value["inlet_pressure_bar"] = float(value.pop("inlet_pressure_pa")) / 1.0e5
        if "outlet_pressure_bar" not in value and "outlet_pressure_pa" in value:
            value["outlet_pressure_bar"] = float(value.pop("outlet_pressure_pa")) / 1.0e5
        if "inlet_temperature_c" not in value and "inlet_temperature_k" in value:
            value["inlet_temperature_c"] = float(value.pop("inlet_temperature_k")) - 273.15
        if model is SealModel.HYBRID:
            value.setdefault("hole_excitation_ratio", 1.0)
            value.setdefault("hole_nz", 40)
            value.setdefault("hole_max_iterations", 180)
            value.setdefault("hole_tolerance", 1.0e-4)
            value.setdefault("hole_first_step_size", 0.01)
            value.setdefault("hole_relaxation_factor", 0.1)
        return value

    def native_from_spec(self, spec: SealSpec, *, node: int) -> Any:
        model = spec.model if isinstance(spec.model, SealModel) else SealModel(str(spec.model))
        values = spec.metadata.get("engineering_input")
        if isinstance(values, Mapping):
            upgraded = self._upgrade_persisted_inputs(model, values)
            return self.native_from_inputs(spec, model, upgraded, node=node)
        if model is SealModel.DIRECT:
            scalars = {key: getattr(spec, key) for key in _COEFFICIENT_KEYS}
            return self.native_from_inputs(spec, model, scalars, node=node)
        raise EngineeringError(
            f"Seal {spec.name!r} uses {model.value} but has no persisted native engineering_input. "
            "Recalculate it in Seal Studio; no guessed or hard-coded seal coefficients will be substituted."
        )


__all__ = ["SealCalculationResult", "SealStudioService"]
