from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from importlib import import_module
from math import pi
from typing import Any, Mapping

import numpy as np

from .domain import BearingCoefficientPoint, EngineeringError, RotorProject, SealModel, SealSpec


@dataclass(slots=True)
class SealCalculationResult:
    """Traceable preview generated by a native ROSS seal model."""

    source_model: SealModel
    native_element: Any
    applied_spec: SealSpec
    coefficients: tuple[BearingCoefficientPoint, ...]
    leakage_kg_s: tuple[float, ...]
    interface_pressure_pa: float | None = None
    iterations: int | None = None
    note: str = ""


class SealStudioService:
    """Native ROSS seal calculation and reconstruction boundary.

    ROSS Studio stores engineering inputs and the chosen model family, never a
    Studio-side reimplementation of labyrinth/hole-pattern/hybrid physics. Preview
    instantiates the native ROSS class. Apply persists the exact inputs needed to
    reconstruct that class during a strict rotor build.
    """

    def __init__(self, ross_module: Any | None = None) -> None:
        self.rs = ross_module

    def _ross(self) -> Any:
        if self.rs is None:
            self.rs = import_module("ross")
        return self.rs

    @staticmethod
    def _class(module: str, name: str) -> type[Any]:
        return getattr(import_module(module), name)

    @staticmethod
    def _finite(value: Any, label: str, *, positive: bool = False, nonnegative: bool = False) -> float:
        number = float(value)
        if not np.isfinite(number):
            raise EngineeringError(f"{label} must be finite; received {value!r}.")
        if positive and number <= 0:
            raise EngineeringError(f"{label} must be > 0; received {number:g}.")
        if nonnegative and number < 0:
            raise EngineeringError(f"{label} must be >= 0; received {number:g}.")
        return number

    @classmethod
    def _speed_rpm(cls, values: Any) -> np.ndarray:
        speed = np.asarray(values, dtype=float)
        if speed.ndim != 1 or speed.size == 0 or not np.all(np.isfinite(speed)):
            raise EngineeringError("Seal frequency_rpm must be a finite one-dimensional vector.")
        if np.any(speed <= 0) or (speed.size > 1 and np.any(np.diff(speed) <= 0)):
            raise EngineeringError("Seal frequency_rpm must be positive and strictly increasing.")
        return speed

    @staticmethod
    def _gas(value: Any) -> dict[str, float] | None:
        if value in (None, "", {}):
            return None
        if not isinstance(value, Mapping):
            raise EngineeringError("gas_composition must be a mapping of species to mole fractions.")
        result = {str(key): float(item) for key, item in value.items()}
        if not result or any(not np.isfinite(item) or item <= 0 for item in result.values()):
            raise EngineeringError("gas_composition values must be positive and finite.")
        return result

    @staticmethod
    def _matrix_point(element: Any, rpm: float) -> BearingCoefficientPoint:
        omega = float(rpm) * 2.0 * pi / 60.0
        k = np.asarray(element.K(omega), dtype=float)
        c = np.asarray(element.C(omega), dtype=float)
        if k.shape[0] < 2 or c.shape[0] < 2:
            raise EngineeringError("ROSS seal did not expose a lateral 2x2 K/C block.")
        values = (k[0, 0], k[0, 1], k[1, 0], k[1, 1], c[0, 0], c[0, 1], c[1, 0], c[1, 1])
        if not all(np.isfinite(float(value)) for value in values):
            raise EngineeringError(f"ROSS seal returned non-finite K/C at {rpm:g} rpm.")
        return BearingCoefficientPoint(
            rpm=float(rpm),
            kxx=float(k[0, 0]), kxy=float(k[0, 1]), kyx=float(k[1, 0]), kyy=float(k[1, 1]),
            cxx=float(c[0, 0]), cxy=float(c[0, 1]), cyx=float(c[1, 0]), cyy=float(c[1, 1]),
        )

    @staticmethod
    def _leakage(element: Any, count: int) -> tuple[float, ...]:
        raw = getattr(element, "seal_leakage", ())
        if raw is None:
            return ()
        values = np.atleast_1d(raw).astype(float)
        if values.size == 1 and count > 1:
            values = np.repeat(values, count)
        return tuple(float(item) for item in values)

    def calculate(
        self,
        project: RotorProject,
        index: int,
        model: SealModel | str,
        inputs: Mapping[str, Any],
    ) -> SealCalculationResult:
        if not 0 <= int(index) < len(project.seals):
            raise EngineeringError(f"Seal index {index} is outside the project seal range.")
        source = project.seals[int(index)]
        model = model if isinstance(model, SealModel) else SealModel(str(model))
        normalized = self.normalize_inputs(project, source, model, inputs)
        native = self.native_from_inputs(source, model, normalized, node=0)
        speeds = normalized.get("frequency_rpm", [project.operating_cases[0].rated_speed_rpm])
        if model is SealModel.DIRECT:
            speeds = [float(project.operating_cases[0].rated_speed_rpm)]
        points = tuple(self._matrix_point(native, float(rpm)) for rpm in speeds)
        nominal = min(points, key=lambda point: abs(point.rpm - project.operating_cases[0].rated_speed_rpm))

        applied = deepcopy(source)
        applied.model = model
        applied.kxx, applied.kxy, applied.kyx, applied.kyy = nominal.kxx, nominal.kxy, nominal.kyx, nominal.kyy
        applied.cxx, applied.cxy, applied.cyx, applied.cyy = nominal.cxx, nominal.cxy, nominal.cyx, nominal.cyy
        applied.metadata = {
            "source_model": model.value,
            "engineering_input": deepcopy(normalized),
        }
        interface = getattr(native, "interface_pressure", None)
        iterations = getattr(native, "n_iterations", None)
        note = {
            SealModel.DIRECT: "Native ROSS SealElement direct K/C preview.",
            SealModel.LABYRINTH: "Native ROSS LabyrinthSeal compressible-flow solve with leakage and pressure field.",
            SealModel.HOLE_PATTERN: "Native ROSS HolePatternSeal bulk-flow solve with leakage and pressure field.",
            SealModel.HYBRID: "Native ROSS HybridSeal mass-flow matched hole-pattern + labyrinth solve.",
        }[model]
        return SealCalculationResult(
            source_model=model,
            native_element=native,
            applied_spec=applied,
            coefficients=points,
            leakage_kg_s=self._leakage(native, len(points)),
            interface_pressure_pa=None if interface is None else float(interface),
            iterations=None if iterations is None else int(iterations),
            note=note,
        )

    def apply(self, project: RotorProject, index: int, result: SealCalculationResult) -> SealSpec:
        if not 0 <= int(index) < len(project.seals):
            raise EngineeringError(f"Seal index {index} is outside the project seal range.")
        project.seals[int(index)] = deepcopy(result.applied_spec)
        project.validate()
        return project.seals[int(index)]

    def normalize_inputs(
        self,
        project: RotorProject,
        spec: SealSpec,
        model: SealModel,
        inputs: Mapping[str, Any],
    ) -> dict[str, Any]:
        raw = dict(inputs)
        if model is SealModel.DIRECT:
            keys = ("kxx", "kyy", "kxy", "kyx", "cxx", "cyy", "cxy", "cyx")
            return {key: self._finite(raw.get(key, getattr(spec, key)), key) for key in keys}

        case = project.operating_cases[0]
        speed = self._speed_rpm(raw.get("frequency_rpm", [max(1.0, case.rated_speed_rpm)]))
        common = {
            "shaft_diameter_mm": self._finite(raw.get("shaft_diameter_mm", 100.0), "shaft diameter", positive=True),
            "inlet_pressure_pa": self._finite(raw.get("inlet_pressure_pa", 500_000.0), "inlet pressure", positive=True),
            "outlet_pressure_pa": self._finite(raw.get("outlet_pressure_pa", 100_000.0), "outlet pressure", nonnegative=True),
            "inlet_temperature_k": self._finite(raw.get("inlet_temperature_k", 300.0), "inlet temperature", positive=True),
            "frequency_rpm": [float(value) for value in speed],
            "gas_composition": self._gas(raw.get("gas_composition", {"Nitrogen": 0.7812, "Oxygen": 0.2096, "Argon": 0.0092})),
        }
        if common["outlet_pressure_pa"] >= common["inlet_pressure_pa"]:
            raise EngineeringError("Seal inlet pressure must be greater than outlet pressure.")

        if model is SealModel.LABYRINTH:
            common.update({
                "radial_clearance_mm": self._finite(raw.get("radial_clearance_mm", 0.3), "radial clearance", positive=True),
                "n_teeth": int(raw.get("n_teeth", 10)),
                "pitch_mm": self._finite(raw.get("pitch_mm", 3.0), "pitch", positive=True),
                "tooth_height_mm": self._finite(raw.get("tooth_height_mm", 3.0), "tooth height", positive=True),
                "tooth_width_mm": self._finite(raw.get("tooth_width_mm", 0.15), "tooth width", positive=True),
                "seal_type": str(raw.get("seal_type", "inter")),
                "preswirl": self._finite(raw.get("preswirl", 0.8), "preswirl"),
                "use_jenny_kanki": bool(raw.get("use_jenny_kanki", False)),
            })
            if common["n_teeth"] < 2:
                raise EngineeringError("LabyrinthSeal requires at least two teeth.")
            return common

        if model is SealModel.HOLE_PATTERN:
            common.update({
                "radial_clearance_mm": self._finite(raw.get("radial_clearance_mm", 0.18), "radial clearance", positive=True),
                "axial_length_mm": self._finite(raw.get("axial_length_mm", 84.9), "axial length", positive=True),
                "relative_roughness": self._finite(raw.get("relative_roughness", 1e-4), "relative roughness", nonnegative=True),
                "cell_length_mm": self._finite(raw.get("cell_length_mm", 2.3), "cell length", positive=True),
                "cell_width_mm": self._finite(raw.get("cell_width_mm", 2.1), "cell width", positive=True),
                "cell_depth_mm": self._finite(raw.get("cell_depth_mm", 2.8), "cell depth", positive=True),
                "preswirl": self._finite(raw.get("preswirl", 1.0), "preswirl"),
                "entrance_loss_coefficient": self._finite(raw.get("entrance_loss_coefficient", 0.1), "entrance loss", nonnegative=True),
                "exit_loss_coefficient": self._finite(raw.get("exit_loss_coefficient", 0.5), "exit loss", nonnegative=True),
                "excitation_ratio": self._finite(raw.get("excitation_ratio", 1.0), "excitation ratio", positive=True),
                "nz": int(raw.get("nz", 40)),
                "max_iterations": int(raw.get("max_iterations", 180)),
                "tolerance": self._finite(raw.get("tolerance", 1e-4), "tolerance", positive=True),
                "first_step_size": self._finite(raw.get("first_step_size", 0.01), "first step", positive=True),
                "relaxation_factor": self._finite(raw.get("relaxation_factor", 0.1), "relaxation factor", positive=True),
            })
            return common

        common.update({
            "hole_radial_clearance_mm": self._finite(raw.get("hole_radial_clearance_mm", 0.30), "hole-pattern clearance", positive=True),
            "hole_axial_length_mm": self._finite(raw.get("hole_axial_length_mm", 40.0), "hole-pattern length", positive=True),
            "hole_relative_roughness": self._finite(raw.get("hole_relative_roughness", 1e-4), "hole-pattern roughness", nonnegative=True),
            "hole_cell_length_mm": self._finite(raw.get("hole_cell_length_mm", 3.0), "hole cell length", positive=True),
            "hole_cell_width_mm": self._finite(raw.get("hole_cell_width_mm", 3.0), "hole cell width", positive=True),
            "hole_cell_depth_mm": self._finite(raw.get("hole_cell_depth_mm", 2.0), "hole cell depth", positive=True),
            "hole_preswirl": self._finite(raw.get("hole_preswirl", 0.8), "hole preswirl"),
            "hole_entrance_loss_coefficient": self._finite(raw.get("hole_entrance_loss_coefficient", 0.5), "hole entrance loss", nonnegative=True),
            "hole_exit_loss_coefficient": self._finite(raw.get("hole_exit_loss_coefficient", 1.0), "hole exit loss", nonnegative=True),
            "lab_radial_clearance_mm": self._finite(raw.get("lab_radial_clearance_mm", 0.25), "labyrinth clearance", positive=True),
            "lab_n_teeth": int(raw.get("lab_n_teeth", 10)),
            "lab_pitch_mm": self._finite(raw.get("lab_pitch_mm", 3.0), "labyrinth pitch", positive=True),
            "lab_tooth_height_mm": self._finite(raw.get("lab_tooth_height_mm", 3.0), "labyrinth tooth height", positive=True),
            "lab_tooth_width_mm": self._finite(raw.get("lab_tooth_width_mm", 0.15), "labyrinth tooth width", positive=True),
            "lab_seal_type": str(raw.get("lab_seal_type", "inter")),
            "lab_preswirl": self._finite(raw.get("lab_preswirl", 0.9), "labyrinth preswirl"),
            "tolerance": self._finite(raw.get("tolerance", 1e-6), "hybrid tolerance", positive=True),
            "max_iterations": int(raw.get("max_iterations", 100)),
        })
        if common["lab_n_teeth"] < 2:
            raise EngineeringError("Hybrid labyrinth stage requires at least two teeth.")
        return common

    def native_from_inputs(self, spec: SealSpec, model: SealModel, values: Mapping[str, Any], *, node: int) -> Any:
        rs = self._ross()
        value = dict(values)
        if model is SealModel.DIRECT:
            return rs.SealElement(
                n=node, tag=spec.name,
                kxx=float(value["kxx"]), kyy=float(value["kyy"]),
                kxy=float(value["kxy"]), kyx=float(value["kyx"]),
                cxx=float(value["cxx"]), cyy=float(value["cyy"]),
                cxy=float(value["cxy"]), cyx=float(value["cyx"]),
            )

        frequency = np.asarray(value["frequency_rpm"], dtype=float) * 2.0 * pi / 60.0
        common = dict(
            n=node,
            shaft_radius=float(value["shaft_diameter_mm"]) / 2000.0,
            inlet_pressure=float(value["inlet_pressure_pa"]),
            outlet_pressure=float(value["outlet_pressure_pa"]),
            inlet_temperature=float(value["inlet_temperature_k"]),
            frequency=frequency,
            gas_composition=value.get("gas_composition"),
            tag=spec.name,
        )
        if model is SealModel.LABYRINTH:
            cls = self._class("ross.seals.labyrinth_seal", "LabyrinthSeal")
            return cls(
                **common,
                radial_clearance=float(value["radial_clearance_mm"]) / 1000.0,
                n_teeth=int(value["n_teeth"]),
                pitch=float(value["pitch_mm"]) / 1000.0,
                tooth_height=float(value["tooth_height_mm"]) / 1000.0,
                tooth_width=float(value["tooth_width_mm"]) / 1000.0,
                seal_type=str(value["seal_type"]),
                preswirl=float(value["preswirl"]),
                iopt1=int(bool(value.get("use_jenny_kanki", False))),
            )
        if model is SealModel.HOLE_PATTERN:
            cls = self._class("ross.seals.holepattern_seal", "HolePatternSeal")
            return cls(
                **common,
                radial_clearance=float(value["radial_clearance_mm"]) / 1000.0,
                length=float(value["axial_length_mm"]) / 1000.0,
                roughness=float(value["relative_roughness"]),
                cell_length=float(value["cell_length_mm"]) / 1000.0,
                cell_width=float(value["cell_width_mm"]) / 1000.0,
                cell_depth=float(value["cell_depth_mm"]) / 1000.0,
                preswirl=float(value["preswirl"]),
                entr_coef=float(value["entrance_loss_coefficient"]),
                exit_coef=float(value["exit_loss_coefficient"]),
                whirl_ratio=float(value["excitation_ratio"]),
                nz=int(value["nz"]), max_iterations=int(value["max_iterations"]),
                tolerance=float(value["tolerance"]), first_step_size=float(value["first_step_size"]),
                rlx_factor=float(value["relaxation_factor"]),
            )

        cls = self._class("ross.seals.hybrid_seal", "HybridSeal")
        hole = {
            "radial_clearance": float(value["hole_radial_clearance_mm"]) / 1000.0,
            "length": float(value["hole_axial_length_mm"]) / 1000.0,
            "roughness": float(value["hole_relative_roughness"]),
            "cell_length": float(value["hole_cell_length_mm"]) / 1000.0,
            "cell_width": float(value["hole_cell_width_mm"]) / 1000.0,
            "cell_depth": float(value["hole_cell_depth_mm"]) / 1000.0,
            "preswirl": float(value["hole_preswirl"]),
            "entr_coef": float(value["hole_entrance_loss_coefficient"]),
            "exit_coef": float(value["hole_exit_loss_coefficient"]),
        }
        lab = {
            "radial_clearance": float(value["lab_radial_clearance_mm"]) / 1000.0,
            "n_teeth": int(value["lab_n_teeth"]),
            "pitch": float(value["lab_pitch_mm"]) / 1000.0,
            "tooth_height": float(value["lab_tooth_height_mm"]) / 1000.0,
            "tooth_width": float(value["lab_tooth_width_mm"]) / 1000.0,
            "seal_type": str(value["lab_seal_type"]),
            "preswirl": float(value["lab_preswirl"]),
        }
        return cls(
            **common,
            hole_pattern_parameters=hole,
            labyrinth_parameters=lab,
            tolerance=float(value["tolerance"]),
            max_iterations=int(value["max_iterations"]),
        )

    def native_from_spec(self, spec: SealSpec, *, node: int) -> Any:
        model = spec.model if isinstance(spec.model, SealModel) else SealModel(str(spec.model))
        if model is SealModel.DIRECT:
            values = {key: getattr(spec, key) for key in ("kxx", "kyy", "kxy", "kyx", "cxx", "cyy", "cxy", "cyx")}
        else:
            values = spec.metadata.get("engineering_input")
            if not isinstance(values, Mapping):
                raise EngineeringError(
                    f"Seal {spec.name!r} uses {model.value} but has no persisted native engineering_input. Recalculate it in Seal Studio."
                )
        return self.native_from_inputs(spec, model, values, node=node)


__all__ = ["SealCalculationResult", "SealStudioService"]
